This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./report-apa.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file report-apa.acn....done (56 entries accepted, 0 rejected).
Sorting entries....done (430 comparisons).
Generating output file report-apa.acr....done (39 lines written, 0 warnings).
Output written in report-apa.acr.
Transcript written in report-apa.alg.
